version: '2'

services:
  apt-cacher-ng:
    restart: always
    image: sameersbn/apt-cacher-ng:0.9.1
    ports:
    - "3142:3142"
    volumes:
    - /srv/docker/apt-cacher-ng:/var/cache/apt-cacher-ng
